name: Add Urgent Label to Issue

on:
    workflow_dispatch:
        inputs:
            name:
            # Friendly description to be shown in the UI instead of 'name'
                description: 'Person to greet'
            # Default value if no value is explicitly provided
                default: 'Daniel'
            # Input has to be provided for the workflow to run
                required: true
                type: string
            
    

jobs:
    label_issues:
        name: Add Urgent Label to Issue
        runs-on: ubuntu-latest
        permissions:
            issues: write
        if: ${{ startsWith(github.event.comment.body, '/URGENT') }}
        steps:
            - name: Set default identity
              run: |
                    git config --global user.email ${{ vars.USER_EMAIL }}
                    git config --global user.name ${{ vars.USER_NAME }}

            - name: Add Label
              uses: actions/github-script@v6
              with:
                script: |
                    github.rest.issues.addLabels({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: ["Urgent"]
                    })
            
            - name: Add Assignee to Issue
              uses: actions/github-script@v6
              with:
                script: |
                    github.rest.issues.addAssignees({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    assignees: ["${{ github.actor }}"]
                    })

