name: Timeout test with regex

on:
    pull_request:
        branches:
            - '[0-9]'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Timeout
              run: sleep 10
    
    confirm:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Confirm
              run: echo "Confirm complete"

                
