name: Test Tag Push

on:
    pull_request:
        branches: [main]  
    push:
        tags:
            - '@rightcapital/**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Run test
              run: echo "Job 1 runs successfully."

    test-2:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Run test
              run: echo "Job 2 runs successfully."