name: Test Tag Push

on:
    push:
        branches: [main]
        tags:
            - 'test/*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Run test
              run: echo "Job 1 runs successfully."

    test-2:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/heads/main') && startsWith(github.ref, 'refs/tags/test/')
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Run test
              run: echo "Job 2 runs successfully."